### ISSUE TITLE
More specific project name

### ISSUE THREAD

**Issue by rakhimov** [OpenReliability/OpenReliability#1]
IMHO, OpenReliability for software sounds too general.
I am not from this field, but something specific to microelectronics:
```latex
open-\mu-e-reliability
```

**Comment by KDB2** [comment]
Project forked, different path, different lives. Good luck for the future.

**Comment by rakhimov** [comment]
@KDB2 I am afraid you are confusing things.
µrel is not a fork.
Hadn't this project been in conflict with openreliability.org,
I wouldn't have cared.

Knowing that you are busy,
I'm trying to help you out.

I booked the name in PyPI for future distribution reasons
so that your package is easier to install for wide-range of users.

The new name is necessary
due to OpenReliability being too general and in conflict with
the @jto888 effort to truly provide a wide range of reliability tools and tutorials
in open-source spirit.
