### ISSUE TITLE
Refactor/Redesign as Veusz Extension

### ISSUE THREAD

**Issue by rakhimov** [OpenReliability/OpenReliability#3]
The current setup as a full-fledged Veusz fork is unmaintainable and highly prone to bit-rot.
According to the Veusz wiki, it supports plugins/addins/extensions.
This approach would make Veusz as the primary dependency,
which is easily available via ``pip``.

**Comment by KDB2** [comment]
Thanks a lot for your attention and opinion. Nevertheless, I strongly disagree with your conclusions. 
The project is not unmaintained even if the commit rate has drastically slowed down. Too much professional work retains my attention at the moment. Nevertheless the project is used in a professional environment and giving good results. 

I am well aware of the capabilities of Veusz and use/will use them. But moving the full project to a extension will not be considered for a lot of different reasons.

I wish you a lot of fun and success with murel.
